[project]
name = "mini-logistic-regression"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
]

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "mini_lr"

[tool.pytest]
testpaths = ["tests"]
filterwarnings = ["error"]
